#scf组件配置样例
#全量配置参考https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
#组件信息
component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: crazyJoy # (必填) 创建的实例名称，请修改成您的实例名称
#组件参数
inputs:
  name: crazyJoy #函数名称
  src: ./  #代码路径
  handler: index.main #入口
  runtime: Nodejs12.16 # 云函数运行时的环境
  region: ap-guangzhou # 云函数所在区域
  memorySize: 64 # 内存大小，单位MB
  timeout: 360 # 函数执行超时时间，单位秒
  events: # 触发器
    - timer: # 定时触发器
        parameters:
          name: jd_crazy_joy_collect # 触发器名称，默认timer-${name}-${stage}
          qualifier: $DEFAULT # 别名配置
          cronExpression: '0/6 * * * * * *'
          enable: true
    - timer: # 定时触发器
        parameters:
          name: jd_crazy_joy_compose # 触发器名称，默认timer-${name}-${stage}
          qualifier: $DEFAULT # 别名配置
          cronExpression: '0 0/10 * * * * *'
          enable: true
  environment: #  环境变量
    variables: #  环境变量对象
      TZ: Asia/Shanghai